M48
; DRILL file {KiCad (6.0.4)} date Fri Jun  2 21:22:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-02T21:22:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.1181Y-2.4705
X3.1181Y-4.8327
X6.2677Y-2.4705
X6.2677Y-4.8327
T0
M30
